# Generated by Django 5.0.5 on 2024-05-09 22:40

from django.db import migrations
from main.models import Methods

def forwards_func(apps, schema_editor):
    Methods.objects.create(name='observation')
    Methods.objects.create(name='speaking')
    Methods.objects.create(name='observation')
    

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
