# Generated by Django 5.0.5 on 2024-05-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('idanswer', models.AutoField(db_column='idAnswer', primary_key=True, serialize=False)),
                ('answerpoints', models.IntegerField(blank=True, db_column='answerPoints', null=True)),
                ('addition', models.TextField(blank=True, db_collation='utf8mb3_general_ci', null=True)),
                ('idquestion', models.IntegerField(blank=True, db_column='idQuestion', null=True)),
                ('idmethod', models.IntegerField(blank=True, db_column='idMethod', null=True)),
            ],
            options={
                'db_table': 'answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classnumber', models.IntegerField(blank=True, db_column='classNumber', null=True)),
                ('classletter', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='classLetter', max_length=1, null=True)),
            ],
            options={
                'db_table': 'classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Methods',
            fields=[
                ('idmethod', models.AutoField(db_column='idMethod', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=200, null=True)),
            ],
            options={
                'db_table': 'methods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('idpoll', models.AutoField(db_column='idPoll', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'polls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('idquestion', models.AutoField(db_column='idQuestion', primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, db_collation='utf8mb3_general_ci', null=True)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='studentName', max_length=15, null=True)),
                ('studentsurname', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='studentSurname', max_length=20, null=True)),
                ('studentlastname', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='studentLastname', max_length=20, null=True)),
                ('classnumber', models.IntegerField(blank=True, db_column='classNumber', null=True)),
                ('classletter', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='classLetter', max_length=1, null=True)),
                ('studentbirthdate', models.DateField(blank=True, db_column='studentBirthDate', null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=16, null=True)),
                ('password', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=16, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
